term xterm-256color

# Font
font_size 18
# font_family Hack Nerd Font Mono
font_family Maple Mono NF CN

# Background image
background_image        ~/.config/images/alone.jpg
background_image_layout cscaled  
background_tint         0.94

# Cursor
cursor_blink_interval   -1
cursor_trail            5
cursor_trail_decay      0.1 0.4
cursor_shape            block
mouse_hide_wait         30

# Window layout
enabled_layouts                     *
remember_window_size                yes
macos_quit_when_last_window_closed  yes
initial_window_width                640
initial_window_height               480

# WINDOW
map cmd+[                   previous_window
map cmd+]                   next_window
hide_window_decorations     titlebar-only
scrollback_lines 6000

select_by_word_characters   @-./_~?&=%+#
clipboard_control           write-clipboard write-primary read-clipboard read-primary

show_hyperlink_targets  yes

# TAB 
tab_bar_edge            top
# fade, slant, separator, powerline
tab_bar_style           slant 

# ============================================================================
# Tmux integration
# NOTE: Tmux prefix is Ctrl+Space
# ============================================================================

# cmd+1~9 => switch to tmux window 1~9 (Tmux: prefix+1~9)
map cmd+1 send_text all \x00\x31
map cmd+2 send_text all \x00\x32
map cmd+3 send_text all \x00\x33
map cmd+4 send_text all \x00\x34
map cmd+5 send_text all \x00\x35
map cmd+6 send_text all \x00\x36
map cmd+7 send_text all \x00\x37
map cmd+8 send_text all \x00\x38
map cmd+9 send_text all \x00\x39

# cmd+T: Create Tmux window (Tmux: prefix + c)
map cmd+t send_text all \x00\x63

# cmd+W: Close current Tmux pane (Tmux: prefix + x)
map cmd+w send_text all \x00\x78

# cmd+R: Rename current Tmux window (Tmux: prefix + ,)
map cmd+r send_text all \x00\x2c

# cmd+H: Switch to the previous Tmux window (Tmux: prefix + p)
map cmd+h send_text all \x00\x70
# cmd+L: Switch to the next Tmux window (Tmux: prefix + n)
map cmd+l send_text all \x00\x6e

# cmd+Z: Switch fullscreen or restore (Tmux: prefix + z)
map cmd+z send_text all \x00\x7a
