bind r source-file ~/.tmux.conf \; display "Reloaded!"
unbind C-b
set -g prefix C-space

set -g mouse on
set -g set-clipboard external
set -g allow-passthrough on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Status bar
set -g status-bg '#313244'
set -g status-fg '#7F849C'
set -g status-justify absolute-centre # right
set -g status-left '#[fg=#cba6f7] #S#F#[fg=black]'
set -g status-right '#[fg=#333333, bg=#313244]'
set-window-option -g window-status-current-style 'fg=#333333, bg=#83A598'

set -g renumber-windows on      # 关掉某个窗口后，编号重排
setw -g allow-rename off        # 禁止活动进程修改窗口名
setw -g automatic-rename off    # 禁止自动命名新窗口
setw -g monitor-activity on     # 非当前窗口有内容更新时在状态栏通知

# panel
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour brightred

set -wg window-status-format "#I #W  "
set -wg window-status-current-format " #I #W#F "
set -wg window-status-separator "|"

set -g base-index         1     # 窗口编号从 1 开始计数
set -g pane-base-index    1     # 窗格编号从 1 开始计数
set -g display-panes-time 10000 # PREFIX-Q 显示编号的驻留时长，单位 ms
set -g status-position top      # 状态栏在顶部

setw -g mode-keys vi
# 绑定esc键为进入复制模式
bind Escape copy-mode 
# 绑定v键为开始选择文本
bind -T copy-mode-vi v send-keys -X begin-selection 

# ╭──────────────────────────────────────────────────────────╮
# │                         Plugins                          │
# ╰──────────────────────────────────────────────────────────╯
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
