return {
  -- "folke/trouble.nvim",
  -- dependencies = { "nvim-tree/nvim-web-devicons" },
  -- config = function()
  --   require("trouble").setup({
  --     -- Core settings
  --     auto_close = true,
  --     auto_open = false,
  --     auto_preview = true,
  --     auto_refresh = true,
  --     auto_jump = true,
  --     focus = false,
  --     restore = true,
  --     follow = true,
  --     indent_guides = true,
  --     max_items = 200,
  --     multiline = true,
  --     pinned = false,
  --     warn_no_results = true,
  --     open_no_results = false,

  --     -- Window options
  --     win = {},
  --     preview = {
  --       type = "main",
  --       scratch = true,
  --     },

  --     -- Throttle/Debounce settings
  --     throttle = {
  --       refresh = 20,
  --       update = 10,
  --       render = 10,
  --       follow = 100,
  --       preview = { ms = 100, debounce = true },
  --     },

  --     -- Key mappings
  --     keys = {
  --       ["?"] = "help",
  --       r = "refresh",
  --       R = "toggle_refresh",
  --       q = "close",
  --       o = "jump_close",
  --       ["<esc>"] = "cancel",
  --       ["<cr>"] = "jump",
  --       ["<2-leftmouse>"] = "jump",
  --       ["<c-s>"] = "jump_split",
  --       ["<c-v>"] = "jump_vsplit",
  --       ["}"] = "next",
  --       ["]]"] = "next",
  --       ["{"] = "prev",
  --       ["[["] = "prev",
  --       dd = "delete",
  --       d = { action = "delete", mode = "v" },
  --       i = "inspect",
  --       p = "preview",
  --       P = "toggle_preview",
  --       zo = "fold_open",
  --       zO = "fold_open_recursive",
  --       zc = "fold_close",
  --       zC = "fold_close_recursive",
  --       za = "fold_toggle",
  --       zA = "fold_toggle_recursive",
  --       zm = "fold_more",
  --       zM = "fold_close_all",
  --       zr = "fold_reduce",
  --       zR = "fold_open_all",
  --       zx = "fold_update",
  --       zX = "fold_update_all",
  --       zn = "fold_disable",
  --       zN = "fold_enable",
  --       zi = "fold_toggle_enable",
  --       -- Custom actions
  --       gb = {
  --         action = function(view)
  --           view:filter({ buf = 0 }, { toggle = true })
  --         end,
  --         desc = "Toggle Current Buffer Filter",
  --       },
  --       s = {
  --         action = function(view)
  --           local f = view:get_filter("severity")
  --           local severity = ((f and f.filter.severity or 0) + 1) % 5
  --           view:filter({ severity = severity }, {
  --             id = "severity",
  --             template = "{hl:Title}Filter:{hl} {severity}",
  --             del = severity == 0,
  --           })
  --         end,
  --         desc = "Toggle Severity Filter",
  --       },
  --     },

  --     -- Mode configurations
  --     modes = {
  --       -- LSP base mode configuration
  --       lsp_base = {
  --         params = {
  --           include_current = false,
  --         },
  --       },
  --       -- LSP references configuration
  --       lsp_references = {
  --         params = {
  --           include_declaration = true,
  --         },
  --       },
  --       -- Symbols mode configuration
  --       symbols = {
  --         desc = "document symbols",
  --         mode = "lsp_document_symbols",
  --         focus = false,
  --         win = { position = "right" },
  --         filter = {
  --           ["not"] = { ft = "lua", kind = "Package" },
  --           any = {
  --             ft = { "help", "markdown" },
  --             kind = {
  --               "Class",
  --               "Constructor",
  --               "Enum",
  --               "Field",
  --               "Function",
  --               "Interface",
  --               "Method",
  --               "Module",
  --               "Namespace",
  --               "Package",
  --               "Property",
  --               "Struct",
  --               "Trait",
  --             },
  --           },
  --         },
  --       },
  --     },

  --     icons = {
  --       indent = {
  --         top = "│ ",
  --         middle = "├╴",
  --         last = "└╴",
  --         fold_open = " ",
  --         fold_closed = " ",
  --         ws = "  ",
  --       },

  --       folder_closed = " ",
  --       folder_open = " ",

  --       kinds = {
  --         Array = " ",
  --         Boolean = "󰨙 ",
  --         Class = " ",
  --         Constant = "󰏿 ",
  --         Constructor = " ",
  --         Enum = " ",
  --         EnumMember = " ",
  --         Event = " ",
  --         Field = " ",
  --         File = " ",
  --         Function = "󰊕 ",
  --         Interface = " ",
  --         Key = " ",
  --         Method = "󰊕 ",
  --         Module = " ",
  --         Namespace = "󰦮 ",
  --         Null = " ",
  --         Number = "󰎠 ",
  --         Object = " ",
  --         Operator = " ",
  --         Package = " ",
  --         Property = " ",
  --         String = " ",
  --         Struct = "󰆼 ",
  --         TypeParameter = " ",
  --         Variable = "󰀫 ",
  --       },
  --     },
  --   })

  --   -- Define keymaps for opening Trouble with different modes
  --   vim.keymap.set("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Toggle Diagnostics (Trouble)" })
  --   vim.keymap.set(
  --     "n",
  --     "<leader>xX",
  --     "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
  --     { desc = "Toggle Buffer Diagnostics (Trouble)" }
  --   )
  --   vim.keymap.set(
  --     "n",
  --     "<leader>cs",
  --     "<cmd>Trouble symbols toggle focus=false<cr>",
  --     { desc = "Toggle Symbols (Trouble)" }
  --   )
  --   vim.keymap.set(
  --     "n",
  --     "<leader>cl",
  --     "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
  --     { desc = "Toggle LSP Definitions/References (Trouble)" }
  --   )
  --   vim.keymap.set("n", "<leader>xL", "<cmd>Trouble loclist toggle<cr>", { desc = "Toggle Location List (Trouble)" })
  --   vim.keymap.set("n", "<leader>xQ", "<cmd>Trouble qflist toggle<cr>", { desc = "Toggle Quickfix List (Trouble)" })

  --   -- Set wrap for Trouble buffer
  --   vim.cmd([[
  --     augroup trouble_setlocal
  --       autocmd!
  --       autocmd FileType trouble setlocal wrap
  --     augroup END
  --   ]])
  -- end,
}
